import type { PortContext } from "../schema.js";
import { toMarkdown, renderSections } from "./markdown.js";
import { toJson } from "./json.js";

function withHeading(heading: string, ctx: PortContext, intro?: string): string {
  const parts: string[] = [heading, ""];
  if (intro) parts.push(intro, "");
  if (ctx.owner) parts.push(`> Owner: ${ctx.owner}`, "");
  return (parts.join("\n") + renderSections(ctx)).trimEnd() + "\n";
}

/** GitHub Copilot custom instructions (`.github/copilot-instructions.md`). */
export function toCopilot(ctx: PortContext): string {
  return withHeading(
    "# Copilot Instructions",
    ctx,
    "Personal context for GitHub Copilot. Generated by portcontext.",
  );
}

/** Claude project memory (`CLAUDE.md`). */
export function toClaude(ctx: PortContext): string {
  return withHeading(
    "# CLAUDE.md",
    ctx,
    "Personal context for Claude. Generated by portcontext.",
  );
}

/** Cursor project rule (`.cursor/rules/portcontext.mdc`) with YAML frontmatter. */
export function toCursor(ctx: PortContext): string {
  const front = [
    "---",
    "description: Personal context and coding preferences",
    "alwaysApply: true",
    "---",
    "",
  ].join("\n");
  const owner = ctx.owner ? `> Owner: ${ctx.owner}\n\n` : "";
  return (front + owner + renderSections(ctx)).trimEnd() + "\n";
}

export interface ExportTarget {
  render: (ctx: PortContext) => string;
  /** Conventional file the tool reads, used by `export --to all`. */
  defaultPath: string;
}

/** All supported export targets keyed by `--to` value. */
export const TARGETS: Record<string, ExportTarget> = {
  markdown: { render: toMarkdown, defaultPath: "AGENTS.md" },
  json: { render: toJson, defaultPath: "context.json" },
  copilot: { render: toCopilot, defaultPath: ".github/copilot-instructions.md" },
  cursor: { render: toCursor, defaultPath: ".cursor/rules/portcontext.mdc" },
  claude: { render: toClaude, defaultPath: "CLAUDE.md" },
};

/** Targets written by `export --to all` (excludes the canonical json). */
export const ALL_TOOL_TARGETS = ["markdown", "copilot", "cursor", "claude"] as const;
